steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
    - -c
    - |
      docker build -t ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE} --build-arg="LICENSE=$$LICENSE" --build-arg="ADMIN_PASS=$$ADMIN_PASSWORD" .
    secretEnv: ['LICENSE', 'ADMIN_PASSWORD']
    timeout: 3600s
timeout: 4500s
images:
- '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}'
substitutions:
  _LOCATION: us-central1
  _REPOSITORY: nessus-builds
  _IMAGE: npro
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/license/versions/latest
    env: 'LICENSE'
  - versionName: projects/$PROJECT_ID/secrets/adminpass/versions/latest
    env: 'ADMIN_PASSWORD'