FROM centos:7
ARG LINKING_KEY=""
ARG SCANNER_NAME=""
ARG MANAGER_HOST=""
ARG MANAGER_PORT=""
ARG PROXY_HOST=""
ARG PROXY_PORT=""
ARG PROXY_USER=""
ARG PROXY_PASS=""
ARG PROXY_AGENT=""
ARG LICENSE=""
ARG ADMIN_USER="admin"
ARG ADMIN_PASS=""

ENV LINKING_KEY=${LINKING_KEY}
ENV SCANNER_NAME=${SCANNER_NAME}
ENV MANAGER_HOST=${MANAGER_HOST}
ENV MANAGER_PORT=${MANAGER_PORT}
ENV PROXY_HOST=${PROXY_HOST}
ENV PROXY_PORT=${PROXY_PORT}
ENV PROXY_USER=${PROXY_USER}
ENV PROXY_PASS=${PROXY_PASS}
ENV PROXY_AGENT=${PROXY_AGENT}
ENV LICENSE=${LICENSE}
ENV ADMIN_USER=${ADMIN_USER}
ENV ADMIN_PASS=${ADMIN_PASS}

COPY quickstart.sh /
CMD ["/quickstart.sh"]